import { Badge } from "@/components/ui/badge";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { Sparkles, Brain, Zap, Bot } from "lucide-react";
import { cn } from "@/lib/utils";

interface CandidateAIProviderBadgeProps {
  source?: string | null;
  aiProvider?: string | null;
  createdByAi?: string | null;
  className?: string;
}

export function CandidateAIProviderBadge({ 
  source, 
  aiProvider, 
  createdByAi,
  className 
}: CandidateAIProviderBadgeProps) {
  const provider = aiProvider || createdByAi || source;
  
  if (!provider) return null;
  
  const providerLower = provider.toLowerCase();
  
  let config = {
    label: "AI",
    icon: Bot,
    color: "bg-muted text-muted-foreground",
    tooltip: "Generated by AI",
  };
  
  if (providerLower.includes("grok") || providerLower.includes("xai")) {
    config = {
      label: "Grok",
      icon: Zap,
      color: "bg-orange-500/20 text-orange-400 border-orange-500/30",
      tooltip: "Generated by Grok (xAI)",
    };
  } else if (providerLower.includes("perplexity") || providerLower === "scheduled_research" || providerLower === "manual") {
    config = {
      label: "Perplexity",
      icon: Sparkles,
      color: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
      tooltip: "Generated by Perplexity AI Research",
    };
  } else if (providerLower.includes("openai") || providerLower.includes("gpt")) {
    config = {
      label: "GPT",
      icon: Brain,
      color: "bg-green-500/20 text-green-400 border-green-500/30",
      tooltip: "Generated by OpenAI GPT",
    };
  } else if (providerLower.includes("anthropic") || providerLower.includes("claude")) {
    config = {
      label: "Claude",
      icon: Brain,
      color: "bg-amber-500/20 text-amber-400 border-amber-500/30",
      tooltip: "Generated by Anthropic Claude",
    };
  } else if (providerLower.includes("groq")) {
    config = {
      label: "Groq",
      icon: Zap,
      color: "bg-purple-500/20 text-purple-400 border-purple-500/30",
      tooltip: "Generated by Groq",
    };
  } else if (providerLower.includes("gemini") || providerLower.includes("google")) {
    config = {
      label: "Gemini",
      icon: Sparkles,
      color: "bg-blue-500/20 text-blue-400 border-blue-500/30",
      tooltip: "Generated by Google Gemini",
    };
  } else if (providerLower === "lab_feedback") {
    config = {
      label: "Evolution",
      icon: Brain,
      color: "bg-violet-500/20 text-violet-400 border-violet-500/30",
      tooltip: "Evolved from LAB feedback loop",
    };
  }
  
  const Icon = config.icon;
  
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Badge 
          variant="outline" 
          className={cn(
            "text-[10px] px-1.5 py-0 h-5 font-medium border gap-1",
            config.color,
            className
          )}
        >
          <Icon className="h-3 w-3" />
          {config.label}
        </Badge>
      </TooltipTrigger>
      <TooltipContent side="top" className="text-xs">
        {config.tooltip}
      </TooltipContent>
    </Tooltip>
  );
}
